let state={oauthConfigured:false,accounts:[]},aid=null,path=[],files=[],selected=new Set(),clipboard=null,sort='name',query='',history={},undo=[];
const app=document.getElementById('app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=n=>{n=Number(n||0);let i=0,u=['B','KB','MB','GB','TB'];while(n>=1024&&i<4){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
function msg(t,type=''){let e=document.querySelector('.status');if(e)e.remove();e=document.createElement('div');e.className='status '+type;e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),4500)}
async function call(p){const r=await p;if(!r.ok){msg(r.error||'Operation failed','error');throw Error(r.error)}return r.data}
const acct=()=>state.accounts.find(x=>+x.id===+aid),folder=()=>path.at(-1)||{id:'root',name:'My Drive'};
function initHistory(){if(!history[aid])history[aid]={items:[path.map(x=>({...x}))],index:0}}
function setPath(next,record=true){path=next.map(x=>({...x}));initHistory();if(record){const h=history[aid];h.items=h.items.slice(0,h.index+1);h.items.push(path.map(x=>({...x})));h.index=h.items.length-1}}
function nav(mode){initHistory();if(mode==='home')setPath([{id:'root',name:'My Drive'}]);else if(mode==='up'){if(path.length<2)return;setPath(path.slice(0,-1))}else{const h=history[aid],i=h.index+(mode==='back'?-1:1);if(i<0||i>=h.items.length)return;h.index=i;path=h.items[i].map(x=>({...x}))}load().then(draw)}
async function load(){files=aid?await call(window.farooqDrive.browse(aid,folder().id)):[];selected.clear()}
async function start(){const savedHistory=history,savedUndo=undo;state=await call(window.farooqDrive.getState());history=savedHistory;undo=savedUndo;if(!state.oauthConfigured)return setup();if(!aid&&state.accounts[0]){aid=state.accounts[0].id;path=[{id:'root',name:'My Drive'}];initHistory()}await load();draw()}
function setup(){app.innerHTML=`<div class="setup"><div class="modal"><div class="brand"><div class="logo">FD</div>FarooqDrive</div><h2>Google Desktop OAuth setup</h2><p>Enter your own Google Desktop OAuth credentials. They are encrypted on this PC.</p><div class="warn">Enable Google Drive API and add all test accounts under Google Auth Platform.</div><div class="field"><label>Client ID</label><input id="cid"></div><div class="field"><label>Client Secret</label><input id="sec" type="password"></div><button class="btn primary" id="save">Save</button></div></div>`;document.getElementById('save').onclick=async()=>{await call(window.farooqDrive.saveOAuth(document.getElementById('cid').value,document.getElementById('sec').value));start()}}
function visible(){return files.filter(f=>f.name.toLowerCase().includes(query)).sort((a,b)=>sort==='size'?a.size-b.size:sort==='modifiedTime'?String(b.modifiedTime).localeCompare(String(a.modifiedTime)):String(a[sort]||'').localeCompare(String(b[sort]||''),undefined,{numeric:true}))}
const picked=()=>files.filter(f=>selected.has(f.id));
function draw(){const a=acct(),rows=visible(),h=history[aid]||{items:[],index:0};app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="logo">FD</div>FarooqDrive</div><div class="muted">GOOGLE ACCOUNTS</div><div class="accounts">${state.accounts.map(x=>`<button data-a="${x.id}" class="${+x.id===+aid?'active':''}"><b>${esc(x.displayName||x.email)}</b><small>${esc(x.email)}</small></button>`).join('')}</div><button class="btn ghost" id="add">＋ Add account</button><button class="btn ghost" id="index">↻ Index managed folders</button></aside><main class="main"><div class="top"><div><h1>${esc(a?.displayName||'FarooqDrive')}</h1><div class="locationbar"><div class="navigation"><button id="back" ${h.index>0?'':'disabled'}>← Back</button><button id="forward" ${h.index<h.items.length-1?'':'disabled'}>→</button><button id="up" ${path.length>1?'':'disabled'}>↑ Up</button><button id="home">⌂ Home</button></div><div class="crumb">${path.map((f,i)=>`<button data-c="${i}">${esc(f.name)}</button>`).join(' / ')}</div></div></div><input id="search" placeholder="Search this folder" value="${esc(query)}"></div><div class="toolbar"><button id="new">＋ New folder</button><button id="upload">⇧ Upload</button><button id="open" ${selected.size?'':'disabled'}>Open</button><button id="download" ${selected.size&&!picked().some(f=>f.isFolder)?'':'disabled'}>Download</button><button id="rename" ${selected.size===1?'':'disabled'}>Rename</button><button id="copy" ${selected.size?'':'disabled'}>Copy</button><button id="cut" ${selected.size?'':'disabled'}>Cut</button><button id="paste" ${clipboard?'':'disabled'}>Paste</button><button id="trash" class="danger-text" ${selected.size?'':'disabled'}>Trash</button><button id="undo" ${undo.length?'':'disabled'}>↶ Undo</button><span class="selected-count">${selected.size?selected.size+' selected':''}</span><select id="sort"><option value="name">Name</option><option value="modifiedTime">Modified</option><option value="size">Size</option><option value="mimeType">Type</option></select><button id="refresh">↻</button></div><section class="panel"><table class="table"><thead><tr><th><input id="all" type="checkbox"></th><th>Name</th><th>Size</th><th>Modified</th><th>Type</th><th>Actions</th></tr></thead><tbody>${rows.map(f=>`<tr><td><input data-s="${f.id}" type="checkbox" ${selected.has(f.id)?'checked':''}></td><td><div class="file-name" data-open="${f.id}"><span>${f.isFolder?'📁':'▤'}</span><b>${esc(f.name)}</b></div></td><td>${f.isFolder?'—':size(f.size)}</td><td>${f.modifiedTime?new Date(f.modifiedTime).toLocaleString():'—'}</td><td>${esc(f.mimeType)}</td><td class="row-actions"><button data-row-open="${f.id}">Open</button>${f.isFolder?'':`<button data-row-download="${f.id}">⇩</button>`}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">This folder is empty.</div>'}</section></main></div>`;bind()}
function bind(){document.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{aid=+b.dataset.a;path=[{id:'root',name:'My Drive'}];await load();draw()});document.querySelectorAll('[data-c]').forEach(b=>b.onclick=async()=>{path=path.slice(0,+b.dataset.c+1);await load();draw()});document.querySelectorAll('[data-s]').forEach(b=>b.onchange=()=>{b.checked?selected.add(b.dataset.s):selected.delete(b.dataset.s);draw()});document.querySelectorAll('[data-open]').forEach(b=>b.ondblclick=async()=>{const f=files.find(x=>x.id===b.dataset.open);if(f.isFolder){path.push({id:f.id,name:f.name});await load();draw()}else if(f.webViewLink)window.open(f.webViewLink)});document.getElementById('all').onchange=e=>{visible().forEach(f=>e.target.checked?selected.add(f.id):selected.delete(f.id));draw()};document.getElementById('search').oninput=e=>{query=e.target.value.toLowerCase();draw()};document.getElementById('sort').value=sort;document.getElementById('sort').onchange=e=>{sort=e.target.value;draw()};document.getElementById('refresh').onclick=async()=>{await load();draw()};document.getElementById('add').onclick=async()=>{state=await call(window.farooqDrive.addAccount());aid=state.accounts.at(-1)?.id;path=[{id:'root',name:'My Drive'}];await load();draw()};document.getElementById('index').onclick=async()=>{const r=await call(window.farooqDrive.sync());state=r.state;msg('Index complete: '+r.count+' file(s).','ok')};document.getElementById('new').onclick=async()=>{const n=prompt('Folder name');if(n){await call(window.farooqDrive.createDriveFolder(aid,folder().id,n));await load();draw()}};document.getElementById('upload').onclick=async()=>{await call(window.farooqDrive.chooseAndUpload(null));await load();draw()};document.getElementById('copy').onclick=()=>{clipboard={mode:'copy',items:picked()};draw();msg('Copied. Open a destination and paste.')};document.getElementById('cut').onclick=()=>{clipboard={mode:'cut',items:picked()};draw();msg('Ready to move. Open a destination and paste.')};document.getElementById('paste').onclick=async()=>{if(clipboard.items.some(f=>+f.accountId!==+aid))return msg('Cross-account transfer uses download then upload in this release.','error');for(const f of clipboard.items){if(clipboard.mode==='copy')await call(window.farooqDrive.copyDriveFile(aid,f.id,folder().id,f.name));else await call(window.farooqDrive.moveDriveFile(aid,f.id,f.parents,folder().id))}if(clipboard.mode==='cut')clipboard=null;await load();draw()};document.getElementById('trash').onclick=async()=>{if(!confirm('Move selected items to Google Drive Trash?'))return;for(const f of picked())await call(window.farooqDrive.trashDriveFile(aid,f.id));await load();draw()}}
function bind(){
  document.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{aid=+b.dataset.a;path=[{id:'root',name:'My Drive'}];initHistory();await load();draw()});
  document.querySelectorAll('[data-c]').forEach(b=>b.onclick=async()=>{setPath(path.slice(0,+b.dataset.c+1));await load();draw()});
  document.querySelectorAll('[data-s]').forEach(b=>b.onchange=()=>{b.checked?selected.add(b.dataset.s):selected.delete(b.dataset.s);draw()});
  const openFile=async id=>{const f=files.find(x=>x.id===id);if(!f)return;if(f.isFolder){setPath([...path,{id:f.id,name:f.name}]);await load();draw()}else if(f.webViewLink)window.open(f.webViewLink)};
  document.querySelectorAll('[data-open]').forEach(b=>b.ondblclick=()=>openFile(b.dataset.open));
  document.querySelectorAll('[data-row-open]').forEach(b=>b.onclick=()=>openFile(b.dataset.rowOpen));
  document.querySelectorAll('[data-row-download]').forEach(b=>b.onclick=async()=>{const f=files.find(x=>x.id===b.dataset.rowDownload);const r=await call(window.farooqDrive.downloadDriveFile(aid,f));if(!r.canceled)msg('Downloaded to '+r.path,'ok')});
  document.getElementById('back').onclick=()=>nav('back');document.getElementById('forward').onclick=()=>nav('forward');document.getElementById('up').onclick=()=>nav('up');document.getElementById('home').onclick=()=>nav('home');
  document.getElementById('all').onchange=e=>{visible().forEach(f=>e.target.checked?selected.add(f.id):selected.delete(f.id));draw()};
  document.getElementById('search').oninput=e=>{query=e.target.value.toLowerCase();draw()};document.getElementById('sort').value=sort;document.getElementById('sort').onchange=e=>{sort=e.target.value;draw()};
  document.getElementById('refresh').onclick=async()=>{await load();draw()};document.getElementById('add').onclick=async()=>{state=await call(window.farooqDrive.addAccount());aid=state.accounts.at(-1)?.id;path=[{id:'root',name:'My Drive'}];initHistory();await load();draw()};
  document.getElementById('index').onclick=async()=>{const r=await call(window.farooqDrive.sync());state=r.state;msg('Index complete: '+r.count+' file(s).','ok')};
  document.getElementById('new').onclick=async()=>{const n=prompt('Folder name')?.trim();if(n){const made=await call(window.farooqDrive.createDriveFolder(aid,folder().id,n));undo.push({type:'created',items:[made]});await load();draw();msg('Folder created — Undo is available.')}};
  document.getElementById('upload').onclick=async()=>{await call(window.farooqDrive.chooseAndUpload(folder().id));await load();draw()};
  document.getElementById('open').onclick=async()=>{for(const f of picked())await openFile(f.id)};
  document.getElementById('download').onclick=async()=>{for(const f of picked()){const r=await call(window.farooqDrive.downloadDriveFile(aid,f));if(!r.canceled)msg('Downloaded to '+r.path,'ok')}};
  document.getElementById('rename').onclick=async()=>{const f=picked()[0],n=prompt('New name',f.name)?.trim();if(n&&n!==f.name){await call(window.farooqDrive.renameDriveFile(aid,f.id,n));undo.push({type:'rename',id:f.id,name:f.name});await load();draw();msg('Renamed — Undo is available.')}};
  document.getElementById('copy').onclick=()=>{clipboard={mode:'copy',items:picked()};draw();msg('Copied. Open a destination and paste.')};document.getElementById('cut').onclick=()=>{clipboard={mode:'cut',items:picked()};draw();msg('Ready to move. Open a destination and paste.')};
  document.getElementById('paste').onclick=async()=>{if(clipboard.items.some(f=>+f.accountId!==+aid))return msg('Cross-account transfer uses download then upload in this release.','error');const u=[];for(const f of clipboard.items){if(clipboard.mode==='copy'){const made=await call(window.farooqDrive.copyDriveFile(aid,f.id,folder().id,f.name));u.push({type:'created',items:[made]})}else{await call(window.farooqDrive.moveDriveFile(aid,f.id,f.parents,folder().id));u.push({type:'move',id:f.id,parents:f.parents,newParent:folder().id})}}undo.push(...u);if(clipboard.mode==='cut')clipboard=null;await load();draw();msg('Paste complete — Undo is available.')};
  document.getElementById('trash').onclick=async()=>{const items=picked();if(!confirm('Move selected items to Google Drive Trash?'))return;for(const f of items)await call(window.farooqDrive.trashDriveFile(aid,f.id));undo.push({type:'trash',items:items.map(f=>f.id)});await load();draw();msg('Moved to Trash — Undo is available.')};
  document.getElementById('undo').onclick=async()=>{const x=undo.pop();if(!x)return;try{if(x.type==='rename')await call(window.farooqDrive.renameDriveFile(aid,x.id,x.name));else if(x.type==='trash')for(const id of x.items)await call(window.farooqDrive.restoreDriveFile(aid,id));else if(x.type==='created')for(const f of x.items)await call(window.farooqDrive.trashDriveFile(aid,f.id));else if(x.type==='move')await call(window.farooqDrive.moveDriveFile(aid,x.id,[x.newParent],x.parents[0]||'root'));await load();draw();msg('Last action undone.','ok')}catch(e){undo.push(x);draw()}};
}
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();nav('back')}else if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();nav('forward')}else if(e.altKey&&e.key==='ArrowUp'){e.preventDefault();nav('up')}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();document.getElementById('undo')?.click()}else if(e.key==='Delete')document.getElementById('trash')?.click();else if(e.key==='F2')document.getElementById('rename')?.click();else if(e.key==='Enter')document.getElementById('open')?.click()});
window.farooqDrive.onUploadProgress(p=>{if(!p.done)msg(`Uploading ${p.file} (${p.index}/${p.total}) — ${p.percent}%`)});start();
