import { Router } from 'express';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { all,get,run } from '../db/database.js';
import { requireAuth } from '../middleware/auth.js';
import { accessTokenForDrive,listRootFiles,patchDriveFile,refreshQuota,revokeDriveAccount,selectDriveForUpload,startResumableUpload,trashDriveFile } from '../services/google.js';

export const driveRouter=Router(); driveRouter.use(requireAuth);
const str=(v:any)=>v==null?null:String(v);

driveRouter.get('/dashboard',(req,res)=>{const accounts=all<any>('SELECT id,email,display_name AS displayName,avatar_url AS avatarUrl,quota_limit AS quotaLimit,quota_usage AS quotaUsage,quota_usage_drive AS quotaUsageDrive,last_synced_at AS lastSyncedAt FROM drive_accounts WHERE user_id=? ORDER BY created_at',[req.userId!]);let total=0n,used=0n,finite=true;for(const a of accounts){if(a.quotaLimit==null)finite=false;else total+=BigInt(a.quotaLimit);used+=BigInt(a.quotaUsage??'0');a.quotaLimit=str(a.quotaLimit);a.quotaUsage=str(a.quotaUsage);a.quotaUsageDrive=str(a.quotaUsageDrive);}const r=get<any>('SELECT COUNT(*) count FROM files WHERE user_id=? AND trashed=0',[req.userId!]);res.json({accounts,totals:{limit:finite?total.toString():null,used:used.toString(),free:finite?(total-used).toString():null},fileCount:Number(r?.count??0)});});
driveRouter.post('/quota/refresh',async(req,res)=>{const rows=all<any>('SELECT id FROM drive_accounts WHERE user_id=?',[req.userId!]);await Promise.allSettled(rows.map(r=>refreshQuota(r.id,req.userId!)));res.json({ok:true});});
driveRouter.delete('/accounts/:id',async(req,res,next)=>{try{await revokeDriveAccount(req.params.id,req.userId!);res.json({ok:true});}catch(e){next(e)}});

driveRouter.post('/uploads/session',async(req,res,next)=>{try{const b=z.object({name:z.string().min(1).max(255),mimeType:z.string().max(255).default('application/octet-stream'),sizeBytes:z.string().regex(/^\d+$/),virtualFolderId:z.string().nullable().optional()}).parse(req.body);const accountId=await selectDriveForUpload(req.userId!,BigInt(b.sizeBytes));const sessionUrl=await startResumableUpload({userId:req.userId!,accountId,name:b.name,mimeType:b.mimeType,sizeBytes:BigInt(b.sizeBytes)});res.json({sessionUrl,accountId,virtualFolderId:b.virtualFolderId??null});}catch(e){next(e)}});
driveRouter.post('/uploads/complete',async(req,res,next)=>{try{const b=z.object({accountId:z.string(),virtualFolderId:z.string().nullable().optional(),file:z.object({id:z.string(),name:z.string(),mimeType:z.string(),size:z.string().optional(),modifiedTime:z.string().optional(),webViewLink:z.string().optional(),iconLink:z.string().optional()})}).parse(req.body);if(!get('SELECT id FROM drive_accounts WHERE id=? AND user_id=?',[b.accountId,req.userId!]))return res.status(403).json({error:'Invalid Drive account'});const existing=get<any>('SELECT id FROM files WHERE drive_account_id=? AND google_file_id=?',[b.accountId,b.file.id]);if(existing)run('UPDATE files SET virtual_folder_id=?,name=?,mime_type=?,size_bytes=?,modified_time=?,web_view_link=?,icon_link=?,trashed=0,updated_at=CURRENT_TIMESTAMP WHERE id=?',[b.virtualFolderId??null,b.file.name,b.file.mimeType,b.file.size??'0',b.file.modifiedTime??null,b.file.webViewLink??null,b.file.iconLink??null,existing.id]);else run('INSERT INTO files (id,user_id,drive_account_id,google_file_id,virtual_folder_id,name,mime_type,size_bytes,modified_time,web_view_link,icon_link) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[nanoid(),req.userId!,b.accountId,b.file.id,b.virtualFolderId??null,b.file.name,b.file.mimeType,b.file.size??'0',b.file.modifiedTime??null,b.file.webViewLink??null,b.file.iconLink??null]);await refreshQuota(b.accountId,req.userId!);res.status(201).json({ok:true});}catch(e){next(e)}});
driveRouter.post('/sync',async(req,res,next)=>{try{const accounts=all<any>('SELECT id FROM drive_accounts WHERE user_id=?',[req.userId!]);let count=0;for(const a of accounts){for(const f of await listRootFiles(a.id,req.userId!)){const existing=get<any>('SELECT id FROM files WHERE drive_account_id=? AND google_file_id=?',[a.id,f.id]);if(existing)run('UPDATE files SET name=?,mime_type=?,size_bytes=?,modified_time=?,web_view_link=?,icon_link=?,trashed=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[f.name,f.mimeType,f.size??'0',f.modifiedTime??null,f.webViewLink??null,f.iconLink??null,f.trashed?1:0,existing.id]);else run('INSERT INTO files (id,user_id,drive_account_id,google_file_id,name,mime_type,size_bytes,modified_time,web_view_link,icon_link,trashed) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[nanoid(),req.userId!,a.id,f.id,f.name,f.mimeType,f.size??'0',f.modifiedTime??null,f.webViewLink??null,f.iconLink??null,f.trashed?1:0]);count++;}run('UPDATE drive_accounts SET last_synced_at=CURRENT_TIMESTAMP WHERE id=?',[a.id]);await refreshQuota(a.id,req.userId!);}res.json({ok:true,synced:count});}catch(e){next(e)}});

driveRouter.get('/files',(req,res)=>{const folder=req.query.folderId?String(req.query.folderId):null;const sql=`SELECT f.id,f.name,f.mime_type AS mimeType,f.size_bytes AS sizeBytes,f.modified_time AS modifiedTime,f.virtual_folder_id AS virtualFolderId,f.web_view_link AS webViewLink,a.email AS driveEmail FROM files f JOIN drive_accounts a ON a.id=f.drive_account_id WHERE f.user_id=? AND f.trashed=0 AND ${folder?'f.virtual_folder_id=?':'f.virtual_folder_id IS NULL'} ORDER BY f.name COLLATE NOCASE`;const rows=all<any>(sql,folder?[req.userId!,folder]:[req.userId!]);rows.forEach(r=>r.sizeBytes=String(r.sizeBytes));res.json(rows);});
driveRouter.get('/folders',(req,res)=>{const parent=req.query.parentId?String(req.query.parentId):null;res.json(all<any>(`SELECT id,name,parent_id AS parentId FROM virtual_folders WHERE user_id=? AND ${parent?'parent_id=?':'parent_id IS NULL'} ORDER BY name COLLATE NOCASE`,parent?[req.userId!,parent]:[req.userId!]));});
driveRouter.post('/folders',(req,res)=>{const b=z.object({name:z.string().min(1).max(255),parentId:z.string().nullable().optional()}).parse(req.body);const id=nanoid();run('INSERT INTO virtual_folders (id,user_id,parent_id,name) VALUES (?,?,?,?)',[id,req.userId!,b.parentId??null,b.name]);res.status(201).json({id,name:b.name,parentId:b.parentId??null});});
driveRouter.patch('/folders/:id',(req,res)=>{const b=z.object({name:z.string().min(1).max(255)}).parse(req.body);run('UPDATE virtual_folders SET name=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?',[b.name,req.params.id,req.userId!]);res.json({ok:true});});
driveRouter.delete('/folders/:id',(req,res)=>{run('UPDATE files SET virtual_folder_id=NULL WHERE virtual_folder_id=? AND user_id=?',[req.params.id,req.userId!]);run('DELETE FROM virtual_folders WHERE id=? AND user_id=?',[req.params.id,req.userId!]);res.json({ok:true});});
driveRouter.patch('/files/:id',async(req,res,next)=>{try{const b=z.object({name:z.string().min(1).max(255).optional(),virtualFolderId:z.string().nullable().optional()}).parse(req.body);const f=get<any>('SELECT drive_account_id accountId,google_file_id googleFileId FROM files WHERE id=? AND user_id=?',[req.params.id,req.userId!]);if(!f)return res.status(404).json({error:'File not found'});if(b.name)await patchDriveFile(f.accountId,req.userId!,f.googleFileId,{name:b.name});if(Object.prototype.hasOwnProperty.call(b,'virtualFolderId'))run('UPDATE files SET virtual_folder_id=?,name=COALESCE(?,name),updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?',[b.virtualFolderId??null,b.name??null,req.params.id,req.userId!]);else run('UPDATE files SET name=COALESCE(?,name),updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?',[b.name??null,req.params.id,req.userId!]);res.json({ok:true});}catch(e){next(e)}});
driveRouter.delete('/files/:id',async(req,res,next)=>{try{const f=get<any>('SELECT drive_account_id accountId,google_file_id googleFileId FROM files WHERE id=? AND user_id=?',[req.params.id,req.userId!]);if(!f)return res.status(404).json({error:'File not found'});await trashDriveFile(f.accountId,req.userId!,f.googleFileId);run('UPDATE files SET trashed=1,updated_at=CURRENT_TIMESTAMP WHERE id=?',[req.params.id]);res.json({ok:true});}catch(e){next(e)}});
driveRouter.get('/files/:id/content',async(req,res,next)=>{try{const f=get<any>('SELECT drive_account_id accountId,google_file_id googleFileId,name,mime_type mimeType FROM files WHERE id=? AND user_id=? AND trashed=0',[req.params.id,req.userId!]);if(!f)return res.status(404).json({error:'File not found'});const token=await accessTokenForDrive(f.accountId,req.userId!);const upstream=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(f.googleFileId)}?alt=media`,{headers:{Authorization:`Bearer ${token}`}});if(!upstream.ok||!upstream.body)return res.status(upstream.status).send(await upstream.text());res.setHeader('Content-Type',f.mimeType||'application/octet-stream');res.setHeader('Content-Disposition',`${req.query.download==='1'?'attachment':'inline'}; filename*=UTF-8''${encodeURIComponent(f.name)}`);const reader=upstream.body.getReader();while(true){const{done,value}=await reader.read();if(done)break;res.write(Buffer.from(value));}res.end();}catch(e){next(e)}});
