import { ChangeEvent,useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { api,API } from '../lib/api';
import { googleAuthorization } from '../lib/googleAuth';
import { UploadPanel } from '../components/UploadPanel';
type Dashboard={accounts:any[];totals:{limit:string|null;used:string;free:string|null};fileCount:number};type FileRow={id:string;name:string;mimeType:string;sizeBytes:string;modifiedTime:string|null;virtualFolderId:string|null;driveEmail:string};type Folder={id:string;name:string;parentId:string|null};type UploadItem={id:string;name:string;progress:number;status:'uploading'|'done'|'error';error?:string};const fmt=(n:string|null)=>n===null?'Unlimited':new Intl.NumberFormat(undefined,{style:'unit',unit:'gigabyte',maximumFractionDigits:2}).format(Number(n)/1e9);
export function DashboardPage(){const[dash,setDash]=useState<Dashboard|null>(null),[files,setFiles]=useState<FileRow[]>([]),[folders,setFolders]=useState<Folder[]>([]),[folderId,setFolderId]=useState<string|null>(null),[uploads,setUploads]=useState<UploadItem[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[search,setSearch]=useState('');const fileInput=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{try{const[d,f,fo]=await Promise.all([api<Dashboard>('/api/drive/dashboard'),api<FileRow[]>(`/api/drive/files${folderId?`?folderId=${folderId}`:''}`),api<Folder[]>(`/api/drive/folders${folderId?`?parentId=${folderId}`:''}`)]);setDash(d);setFiles(f);setFolders(fo)}catch(e:any){if(e.message==='Unauthenticated')location.href='/';else setError(e.message)}},[folderId]);useEffect(()=>{load()},[load]);const shownFiles=useMemo(()=>files.filter(f=>f.name.toLowerCase().includes(search.toLowerCase())),[files,search]);const shownFolders=useMemo(()=>folders.filter(f=>f.name.toLowerCase().includes(search.toLowerCase())),[folders,search]);
 async function action(label:string,fn:()=>Promise<any>){setBusy(label);setError('');try{await fn();await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function connect(){setBusy('Connecting…');try{await googleAuthorization('connect',s=>setBusy(s));await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function makeFolder(){const name=prompt('Folder name');if(name)await action('Creating folder…',()=>api('/api/drive/folders',{method:'POST',body:JSON.stringify({name,parentId:folderId})}))}
 async function renameFolder(f:Folder){const name=prompt('New folder name',f.name);if(name&&name!==f.name)await action('Renaming…',()=>api(`/api/drive/folders/${f.id}`,{method:'PATCH',body:JSON.stringify({name})}))}
 async function deleteFolder(f:Folder){if(confirm(`Delete virtual folder “${f.name}”? Files will return to the virtual root and remain in Google Drive.`))await action('Deleting…',()=>api(`/api/drive/folders/${f.id}`,{method:'DELETE'}))}
 async function rename(f:FileRow){const name=prompt('New file name',f.name);if(name&&name!==f.name)await action('Renaming…',()=>api(`/api/drive/files/${f.id}`,{method:'PATCH',body:JSON.stringify({name})}))}
 async function move(f:FileRow){const target=prompt('Paste a virtual folder ID, or leave blank for root.','');await action('Moving…',()=>api(`/api/drive/files/${f.id}`,{method:'PATCH',body:JSON.stringify({virtualFolderId:target||null})}))}
 async function del(f:FileRow){if(confirm(`Move “${f.name}” to Google Drive trash?`))await action('Deleting…',()=>api(`/api/drive/files/${f.id}`,{method:'DELETE'}))}
 function updateUpload(id:string,p:Partial<UploadItem>){setUploads(prev=>prev.map(x=>x.id===id?{...x,...p}:x))}async function uploadOne(file:File){const id=crypto.randomUUID();setUploads(p=>[...p,{id,name:file.name,progress:0,status:'uploading'}]);try{const plan=await api<any>('/api/drive/uploads/session',{method:'POST',body:JSON.stringify({name:file.name,mimeType:file.type||'application/octet-stream',sizeBytes:String(file.size),virtualFolderId:folderId})});const uploaded:any=await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',plan.sessionUrl);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)updateUpload(id,{progress:Math.round(e.loaded/e.total*100)})};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve(JSON.parse(xhr.responseText)):reject(new Error(`Google upload failed (${xhr.status})`));xhr.onerror=()=>reject(new Error('Network error during Google upload'));xhr.send(file)});await api('/api/drive/uploads/complete',{method:'POST',body:JSON.stringify({accountId:plan.accountId,virtualFolderId:folderId,file:uploaded})});updateUpload(id,{progress:100,status:'done'});await load()}catch(e:any){updateUpload(id,{status:'error',error:e.message})}}async function chooseFiles(e:ChangeEvent<HTMLInputElement>){for(const f of (Array.from(e.target.files||[]) as File[]))await uploadOne(f);e.target.value=''}
 if(!dash)return <div className="loading">Loading FarooqDrive…</div>;const pct=dash.totals.limit?Math.min(100,Number(BigInt(dash.totals.used)*100n/BigInt(dash.totals.limit))):0;
 return <div className="app-shell"><aside><div className="side-brand"><div className="logo">FD</div><div><b>FarooqDrive</b><small>Desktop</small></div></div><nav><button className="active">▦ Dashboard</button><button onClick={()=>setFolderId(null)}>◫ My Files</button></nav><div className="side-bottom"><button onClick={()=>location.href="/settings"}>⚙ OAuth settings</button><button onClick={connect}>＋ Add Drive account</button><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});location.href='/'}}>Sign out</button></div></aside><main className="content"><header><div><h1>Storage dashboard</h1><p>{dash.accounts.length} connected Google Drive account{dash.accounts.length===1?'':'s'}</p></div><div className="actions"><button onClick={()=>action('Syncing…',()=>api('/api/drive/sync',{method:'POST'}))}>↻ Sync</button><button onClick={()=>fileInput.current?.click()} className="primary">↑ Upload files</button><input ref={fileInput} type="file" multiple hidden onChange={chooseFiles}/></div></header>{(error||busy)&&<div className={`notice ${error?'error':''}`}>{error||busy}</div>}
 <section className="stats"><div><span>Total storage</span><strong>{fmt(dash.totals.limit)}</strong></div><div><span>Used</span><strong>{fmt(dash.totals.used)}</strong></div><div><span>Free</span><strong>{fmt(dash.totals.free)}</strong></div><div><span>Files</span><strong>{dash.fileCount}</strong></div></section>
 <section className="quota-card"><div className="quota-head"><div><h2>Connected storage</h2><p>Combined quota across your authorized accounts.</p></div><button onClick={()=>action('Refreshing quota…',()=>api('/api/drive/quota/refresh',{method:'POST'}))}>Refresh quota</button></div>{dash.totals.limit&&<><div className="quota-track"><div style={{width:`${pct}%`}}/></div><small>{pct}% used</small></>}<div className="accounts">{dash.accounts.map(a=><div className="account" key={a.id}><div className="avatar">{a.email[0].toUpperCase()}</div><div className="account-name"><b>{a.displayName||a.email}</b><span>{a.email}</span></div><div className="account-space">{fmt(a.quotaUsage)} / {fmt(a.quotaLimit)}</div><button className="icon-btn danger" title="Disconnect" onClick={()=>confirm(`Disconnect ${a.email}? Files stay in Google Drive.`)&&action('Disconnecting…',()=>api(`/api/drive/accounts/${a.id}`,{method:'DELETE'}))}>×</button></div>)}</div></section>
 <section className="files-card"><div className="files-head"><div><h2>{folderId?'Virtual folder':'My files'}</h2><p>Virtual organization; original file bytes stay in Google Drive.</p></div><div className="file-tools"><input className="search" placeholder="Search here…" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={makeFolder}>＋ New folder</button>{folderId&&<button onClick={()=>setFolderId(null)}>← Root</button>}</div></div><div className="table"><div className="tr th"><span>Name</span><span>Size</span><span>Drive</span><span>Modified</span><span>Actions</span></div>{shownFolders.map(f=><div className="tr" key={f.id}><span className="file-name folder-name" onDoubleClick={()=>setFolderId(f.id)}>📁 {f.name}</span><span>—</span><span>Virtual</span><span>—</span><span className="row-actions"><button onClick={()=>setFolderId(f.id)}>Open</button><button onClick={()=>renameFolder(f)}>Rename</button><button className="danger-text" onClick={()=>deleteFolder(f)}>Delete</button></span></div>)}{shownFiles.map(f=><div className="tr" key={f.id}><span className="file-name">📄 {f.name}</span><span>{fmt(f.sizeBytes)}</span><span title={f.driveEmail}>{f.driveEmail}</span><span>{f.modifiedTime?new Date(f.modifiedTime).toLocaleString():'—'}</span><span className="row-actions"><a href={`${API}/api/drive/files/${f.id}/content`} target="_blank">Preview</a><a href={`${API}/api/drive/files/${f.id}/content?download=1`}>Download</a><button onClick={()=>rename(f)}>Rename</button><button onClick={()=>move(f)}>Move</button><button className="danger-text" onClick={()=>del(f)}>Delete</button></span></div>)}{!shownFolders.length&&!shownFiles.length&&<div className="empty">No matching files or folders.</div>}</div></section></main><UploadPanel items={uploads}/></div>}
